# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d521a475771850823cbb03fb1e8d48653ce6add0586d5043a0538c17315f59192241ff40caeaa802703b6a77307208785e741f2b8ac53460a3b6e9cb7c85dc

test:
  secret_key_base: bf54f839a57ca3572e21761ec3fc1aff69d004123ee19df93ced86dacf29c0d96ce5a4bf10793cd09b0511ad2ab72275ece3507c4ce25d4018ffe88cf55a0e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
